name = "PlanckFunctions"
uuid = "56edaee7-e77f-43d7-994d-8307b8de0a62"
authors = ["Roman Mironov"]
version = "1.0.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[compat]
DelimitedFiles = "1.9.1"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
